apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitor-config
  namespace: monitoring 
spec:
  interval: 5m
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: monitoring-repo
    namespace: flux-system
  path: ./monitoring/monitoring-config/manifests
  prune: true
