apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
spec:
  hosts:
  - grafana.com
  gateways:
  - istio-ingress
  http:
    - route:
      host: kube-prometheus-stack-grafana.kube-system.svc.cluster.local.

