apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
  namespace: mornitoring
spec:
  hosts:
    - grafana.jason.com
  gateways:
    - ingress-gateway.istio-ingress
  http:
  - route:
    - destination:
       host: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
       port: 
         number: 80
    timeout: 30s

